name             'template_cookbook'
maintainer       'your name here'
maintainer_email 'your address here'
license          'your license here'
description      'convenient repository template'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.3.2'
depends                  'apache2'
depends         'php'
depends         'awscli'